version: '3'
services:
  airflow-scheduler:
    build: ./docker
    volumes:
      - "./dags:/opt/airflow/dags"
      - "./data:/data"
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql://postgres:postgres@postgres:5432/airflow"
      AIRFLOW__CORE__LOAD_EXAMPLES: False
    depends_on:
      - postgres
    command: "scheduler"

  airflow-webserver:
    build: ./docker
    volumes:
      - "./dags:/opt/airflow/dags"
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql://postgres:postgres@postgres:5432/airflow"
      AIRFLOW__CORE__LOAD_EXAMPLES: False
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    command: "webserver"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: airflow
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./data:/data"
